<table width="100%" align="center">
    <tr>
        <td align="center">
            <table border="1">
                <tr>
                    <td>Rut</td>
                    <td><?php echo $this->element->getElement('per_nrut') ?></td>
                </tr>
                <tr>
                    <td>Digito</td>
                    <td><?php echo $this->element->getElement('per_drut') ?></td>
                </tr>
                <tr>
                    <td>Nombre</td>
                    <td><?php echo $this->element->getElement('per_nombre') ?></td>
                </tr>
                <tr>
                    <td>Apellido</td>
                    <td><?php echo $this->element->getElement('per_apellido') ?></td>
                </tr>
                <tr>
                    <td>Tipo</td>
                    <td><?php echo $this->element->getElement('tppr_id') ?></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->element->getElement('submit') ?></td>
    </tr>
</table>