<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=UTF-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
    <?php echo $this->headScript()->prependFile('http://code.jquery.com/jquery-latest.js'); ?>
    <?php echo $this->headScript()->prependFile('/js/funciones_generales.js'); ?>
</head>
<body>
<center><div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div></center>
</body>
</html>