<?php
$this->title = "Eliminar Persona";
$this->headTitle($this->title);
?>
<p>Estas seguro que deseas eliminar a 
  '<?php echo $this->escape($this->Persona['per_nombre']); ?>'
</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->Persona['per_id']; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>